### ISSUE TITLE
Easing the setup development process 

### ISSUE THREAD

**Issue by DarkninjaD** [mkborland/TACT#23]
# Easing the Setup Dev Process 
As a onboarding dev I found some hick-ups in the setup process so I went over and made some changes.

## Problem 1
Seeding & Migrations script on the server side is to quick and would fail out before the db postgre did it's init setup and open for connections.

## Problem 2 
Whenever the sever side had to be restarted it would always want to seed and migrate but if the data base was already filled with data that would lead to errors.

**Comment by DarkninjaD** [comment]
# Solution.
1. Decouple db standing up with server thought docker-compose.
2. Add options to start up script to run server so you can pick when to seed & migrate and when not to.
3. Add it to README to help future on boarding devs.

**Comment by mkborland** [comment]
wrong repo
